-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 16:50:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simple_chat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `simple_chat` ;

-- -----------------------------------------------------
-- Schema simple_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple_chat` DEFAULT CHARACTER SET utf8 ;
USE `simple_chat` ;

-- -----------------------------------------------------
-- Table `simple_chat`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`user_info` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(60) NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL COMMENT '昵称',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `age` TINYINT NULL,
  `sex` BIT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_chat`.`chat_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`chat_group` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`chat_group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL COMMENT '群名称',
  `notice` VARCHAR(300) NULL COMMENT '群公告',
  `admin_id` INT NOT NULL COMMENT '管理员用户id',
  `creator_id` INT NOT NULL COMMENT '创建人id',
  `introduce` VARCHAR(300) NULL COMMENT '简介',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '聊天组';


-- -----------------------------------------------------
-- Table `simple_chat`.`chat_group_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`chat_group_user_relation` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`chat_group_user_relation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '用户id',
  `group_id` INT NOT NULL COMMENT '组id',
  `user_card` VARCHAR(45) NULL COMMENT '群名片',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '聊天组用户关联表';


-- -----------------------------------------------------
-- Table `simple_chat`.`friend_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`friend_group` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`friend_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '用户id',
  `name` VARCHAR(45) NOT NULL COMMENT '分组名',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '用户朋友分组';


-- -----------------------------------------------------
-- Table `simple_chat`.`user_friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`user_friend` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`user_friend` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '用户id',
  `user_friend_id` INT NOT NULL COMMENT '用户朋友id',
  `friend_note` VARCHAR(60) NULL COMMENT '朋友备注昵称',
  `friend_group_id` INT NOT NULL COMMENT '朋友所属分组id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_chat`.`chat_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_chat`.`chat_message` ;

CREATE TABLE IF NOT EXISTS `simple_chat`.`chat_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT '消息类型(TEXT-文本)',
  `is_new` BIT NOT NULL DEFAULT 1 COMMENT '是否新消息(未读)',
  `sender_id` INT NOT NULL COMMENT '发送者id',
  `receiver_id` INT NOT NULL COMMENT '接收用户id',
  `content` TEXT NOT NULL COMMENT '消息内容',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
