#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/simple_chat
#    url: jdbc:mysql://localhost:3306/simple_chat
#    username: root
#    password: tiger
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9500

swagger:
  docket:
    api-info:
      contact:
        name: Wilson
        email: 845023508@qq.com
#debug: true
logging:
  config: classpath:logback-spring.xml
