swagger:
  docket:
    base-package: per.wilson.chat.controller

mybatis-plus:
  mapper-locations: classpath:/mappers/**
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_chat?serverTimezone=UTC
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver